<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Masuk</name>
   <tag></tag>
   <elementGuidId>b21dfb84-68b0-4969-826f-27ca5c50c3b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.dcd-btn.dcd-btn-outline-primary.mr-2.my-sm-0.d-none.d-lg-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarSupportedContent']/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bc99c1b6-ecf3-42a9-8072-de72c30ce2a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.dicoding.com/login</value>
      <webElementGuid>b16ea6e1-b53b-47f2-a86f-b1b079a38b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dcd-btn dcd-btn-outline-primary mr-2 my-sm-0 d-none d-lg-block</value>
      <webElementGuid>58ca2b88-5ced-42b7-9239-5f879af18ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>14d6ac3a-863e-4121-b71f-7bcd994d69f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#login-modal</value>
      <webElementGuid>13f0cdda-24fe-498a-ab2a-57fd7c501a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>45f0d7a3-270d-4f0d-a58a-3c5f2496e5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarSupportedContent&quot;)/div[@class=&quot;navbar-menu-wrapper d-flex align-items-stretch w-100&quot;]/ul[@class=&quot;navbar-nav navbar-nav-right&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;dcd-btn dcd-btn-outline-primary mr-2 my-sm-0 d-none d-lg-block&quot;]</value>
      <webElementGuid>9fcf6698-c925-40e6-bf19-66a4c7839c3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/div/ul/li/a</value>
      <webElementGuid>5ec084ee-c254-4bbb-a0e9-2af4cff2ffe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Masuk')]</value>
      <webElementGuid>144a7265-c270-4186-bff1-493bb0723a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tukarkan point dengan reward menarik.'])[1]/following::a[1]</value>
      <webElementGuid>1159418d-27c8-440a-9a76-961403e73722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ikuti event dan bangun jaringan developer.'])[1]/following::a[2]</value>
      <webElementGuid>70668261-6d92-41ae-a99d-242291fba4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/preceding::a[1]</value>
      <webElementGuid>1b762a58-bcd4-463b-8e5c-5d6522e46316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat semua kelas'])[2]/preceding::a[3]</value>
      <webElementGuid>cd342d1e-03be-40fe-b056-579e4a535a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masuk']/parent::*</value>
      <webElementGuid>48f225c2-facc-4efb-93dd-9e95a854792e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.dicoding.com/login')]</value>
      <webElementGuid>9ca62cf6-b07c-413b-b561-df26858c6be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/a</value>
      <webElementGuid>cbecb959-2468-4e40-a0dc-9229561687d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.dicoding.com/login' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>1312bce9-da8c-4e03-b7d7-862e0adaf56a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
